#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 5 <<< " Lock| Logout| Suspend|  Reboot| Shutdown")"
            case "$MENU" in
                *Lock) betterlockscreen --off 15 -l dimblur ;;
                *Logout) i3-msg exit;;
		*Suspend) i3exit suspend;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
