#!/usr/bin/env bash

count=0
disconnected=""
disconnected1="Nah!"
wireless_connected=""
ethernet_connected=""

SSID_NAME=$(iwgetid -r)
ID="$(ip link | awk '/state UP/ {print $2}')"
route_id="$(ip route | grep -Po '(?<=via )(\d{1,3}.){4}')"

while true; do
  if (ping -c 1 "$route_id")  &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 25
        else
            echo "$wireless_connected" "${SSID_NAME}"; sleep 5
        fi
    else
        echo "$disconnected" "$disconnected1"; sleep 0.5
    fi
done
